if sprache == "english" or sprache == "English" then
  chunkloaderOK             = "- ChunkLoader          ok (optional)"
  chunkloaderFehlt          = "- ChunkLoader          missing (optional)"
  generatorOK               = "- Generator            ok (optional)"
  generatorFehlt            = "- Generator            missing (optional)"
  InternetOK                = "- Internet             ok (optional)"
  InternetFehlt             = "- Internet             missing (optional)"
  inventory_controllerOK    = "- Inventory Controller ok\n"
  inventory_controllerFehlt = "- Inventory Controller missing\n"
  derzeitigeVersion         = "\nCurrect Version:       "
  verfügbareVersion         = "\nAvailable Version:     "
  aktualisierenFrage        = "\nUpdate? yes/no\n"
  aktualisierenJa           = "\nUpdate: yes\n"
  aktualisierenNein         = "\nAnswer: "
else
  chunkloaderOK             = "- ChunkLoader          ok (optional)"
  chunkloaderFehlt          = "- ChunkLoader          fehlt (optional)"
  generatorOK               = "- Generator            ok (optional)"
  generatorFehlt            = "- Generator            fehlt (optional)"
  InternetOK                = "- Internet             ok (optional)"
  InternetFehlt             = "- Internet             fehlt (optional)"
  inventory_controllerOK    = "- Inventory Controller ok\n"
  inventory_controllerFehlt = "- Inventory Controller fehlt\n"
  derzeitigeVersion         = "\nDerzeitige Version:    "
  verfügbareVersion         = "\nVerfügbare Version:    "
  aktualisierenFrage        = "\nAktualisieren? ja/nein\n"
  aktualisierenJa           = "\nAktualisieren: Ja\n"
  aktualisierenNein         = "\nAntwort: "
end
